ALL_SCALES = {
    'MODTAS': [
        "Please rate how frequent the following experiences are for you. [Sometimes I feel and experience things as I did when I was a child.]",
        "Please rate how frequent the following experiences are for you. [I can be greatly moved by eloquent or poetic language.]",
        "Please rate how frequent the following experiences are for you. [While watching a movie, a T.V. show, or a play, I may become so involved that I forgot about myself and my surroundings, and experience the story as if it were real and as if I were taking part in it.]",
        "Please rate how frequent the following experiences are for you. [If I stare at a picture and then look away from it, I can “see” an image of the picture, almost as if I were still looking at it.]",
        "Please rate how frequent the following experiences are for you. [Sometimes I feel as if my mind could envelop the whole world.]",
        "Please rate how frequent the following experiences are for you. [I like to watch cloud shapes change in the sky.]",
        "Please rate how frequent the following experiences are for you. [If I wish I can imagine (or daydream) some things so vividly that it’s like watching a good movie or hearing a good story.]",
        "Please rate how frequent the following experiences are for you. [I think I really know what some people mean when they talk about mystical experiences.]",
        "Please rate how frequent the following experiences are for you. [I sometimes “step outside” my usual self and experience a completely different state of being.]",
        "Please rate how frequent the following experiences are for you. [Textures—such as wool, sand, wood—sometimes remind me of colors or music.]",
        "Please rate how frequent the following experiences are for you. [Sometimes I experience things as if they were doubly real.]",
        "Please rate how frequent the following experiences are for you. [When I listen to music I can get so caught up in it that I don’t notice anything else.]",
        "Please rate how frequent the following experiences are for you. [If I wish I can imagine that my body is so heavy that I cannot move it.]",
        "Please rate how frequent the following experiences are for you. [I can somehow sense the presence of another person before I actually see or hear her/him.]",
        "Please rate how frequent the following experiences are for you. [The crackle and flames of a wood fire stimulate my imagination.]",
        "Please rate how frequent the following experiences are for you. [Sometimes I am so immersed in nature or in art that I feel as if my whole state of consciousness has somehow been temporarily changed.]",
        "Please rate how frequent the following experiences are for you. [Different colors have distinctive and special meanings for me.]",
        "Please rate how frequent the following experiences are for you. [I can so completely wander off into my own thoughts while doing a routine task that I actually forget that I am doing the task and find a few minutes later that I have finished it.]",
        "Please rate how frequent the following experiences are for you. [I can sometimes recall certain past experiences in my life so clearly and vividly that it is like living them again, or almost so.]",
        "Please rate how frequent the following experiences are for you. [Things that might seem meaningless to others often make sense to me.]",
        "Please rate how frequent the following experiences are for you. [If I acted in a play I think I would really feel the emotions of the character and “become” that person for the time being, forgetting both myself and the audience.]",
        "Please rate how frequent the following experiences are for you. [My thoughts often occur as visual images rather than as words.]",
        "Please rate how frequent the following experiences are for you. [I am often delighted by small things (like the colors in soap bubbles and the five-pointed star shape that appears when you cut an apple across the core).]",
        "Please rate how frequent the following experiences are for you. [When listening to organ music or other powerful music, I sometimes feel as if I am being lifted into the air.]",
        "Please rate how frequent the following experiences are for you. [Sometimes I can change noise into music by the way I listen to it.]",
        "Please rate how frequent the following experiences are for you. [Some of my most vivid memories are called up by scents and smells.]",
        "Please rate how frequent the following experiences are for you. [Some music reminds me of pictures or changing patterns of color.]",
        "Please rate how frequent the following experiences are for you. [I often know what someone is going to say before he or she says it.]",
        "Please rate how frequent the following experiences are for you. [I often have “physical memories”; for example, after I’ve been swimming I may feel as if I’m still in the water.]",
        "Please rate how frequent the following experiences are for you. [The sound of a voice can be so fascinating to me that I can just go on listening to it.]",
        "Please rate how frequent the following experiences are for you. [At times I somehow feel the presence of someone who is not physically there.]",
        "Please rate how frequent the following experiences are for you. [Sometimes thoughts and images come to me without any effort on my part.]",
        "Please rate how frequent the following experiences are for you. [I find that different smells have different colors.]",
        "Please rate how frequent the following experiences are for you. [I can be deeply moved by a sunset.]"
    ],
    # TODO - Add more scale questions as needed
}
